### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by SirRedrick** [SirRedrick/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by SirCrimson** [comment]
### Ryu Hoshi (リュウ Ryū)
* https://www.facebook.com/profile.php?id=100004808958030
* ryuwins@gmail.com
* https://twitter.com/denjinryu
* https://www.instagram.com/sworn_ryu/
